title: "Weaver // Hunter"
author: "Dee Pennyway"
favicon: "favicon.png"
googlefonts:
    title: "Pirata One"
    heading: "Iceberg"
    body: "EB Garamond"
    sidebar: "EB Garamond"
    dropcap: "Yanone Kaffeesatz"
style:
    accent: "#4E6E5A"
    sidebartext: "#444"
    sidebarback: "var(--accent)"
    paperbg: "#f9f4e9"
    paper: "stone.png"
    cover: "green-book.png"
    coveraccent: "#efefef"
    coverbg: "#39483e"
    sidebartexture: "paper-old.png"
    bodycolor: "#444"
    velvet: "burlwood.png"
    texture: "diamonds.png"
    bgaccent: "#ddd"
    background: "water.jpg"